openapi: 3.0.0
info:
  title: Silmedy_User
  version: 1.0.0
servers:
  - url: http://43.201.73.161:5000
paths:
  /request-verification-code:
    post:
      summary: 인증번호 요청
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                  example: "01012345678"
      responses:
        '200':
          description: 인증번호 발송 성공