swagger: "2.0"
info:
  title: Silmedy_User
  version: 1.0.0
host: 192.168.0.170:5000
basePath: /
schemes:
  - http

securityDefinitions:
  JWT:
    type: apiKey
    name: Authorization
    in: header

paths:
  /patient/signup:
    post:
      summary: 환자 회원가입
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              name:
                type: string
              contact:
                type: string
              postal_code:
                type: string
              address:
                type: string
              address_detail:
                type: string
              birth_date:
                type: string
              sign_language_needed:
                type: boolean
              is_default_address:
                type: boolean
      responses:
        '200':
          description: 환자 등록 성공
        '409':
          description: 이메일 중복
        '500':
          description: 서버 오류

  /patient/login:
    post:
      summary: 환자 로그인
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: 로그인 성공
        '400':
          description: 필수 입력 누락
        '401':
          description: 로그인 실패
        '500':
          description: 서버 오류

  /patient/fcm-token:
    post:
      summary: FCM 토큰 등록
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              fcm_token:
                type: string
                description: FCM token to register
      responses:
        '200':
          description: FCM 토큰 저장 성공
        '400':
          description: FCM 토큰 누락
        '404':
          description: 사용자 없음
        '500':
          description: 서버 오류

  /postal_code:
    get:
      summary: 우편번호 검색
      parameters:
        - in: query
          name: keyword
          required: true
          type: string
          description: 검색 키워드
      responses:
        '200':
          description: 우편번호 리스트 반환
        '400':
          description: 키워드 누락
        '500':
          description: 서버 오류

  /patient/repassword:
    post:
      summary: 환자 비밀번호 변경
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              new_password:
                type: string
      responses:
        '200':
          description: 비밀번호 변경 성공
        '400':
          description: 입력 누락
        '404':
          description: 사용자 없음
        '500':
          description: 서버 오류

  /patient/logout:
    post:
      summary: 환자 로그아웃
      responses:
        '200':
          description: 로그아웃 성공

  /patient/mypage:
    get:
      summary: 환자 마이페이지 조회
      responses:
        '200':
          description: 마이페이지 데이터 반환
        '400':
          description: 환자 ID 누락
        '404':
          description: 사용자 없음

  /patient/update:
    post:
      summary: 회원 정보 수정
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              updates:
                type: object
                description: 수정할 필드 딕셔너리
      responses:
        '200':
          description: 정보 수정 성공
        '400':
          description: 업데이트 항목 누락
        '404':
          description: 사용자 없음
        '500':
          description: 서버 오류

  /patient/delete:
    delete:
      summary: 회원 탈퇴
      responses:
        '200':
          description: 회원 탈퇴 완료
        '400':
          description: 환자 ID 누락
        '404':
          description: 사용자 없음

  /request-verification-code:
    post:
      summary: 인증번호 요청
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              phone_number:
                type: string
                description: 전화번호
      responses:
        '200':
          description: 인증번호 발송됨
        '400':
          description: 전화번호 누락 또는 형식 오류

  /verify-code:
    post:
      summary: 인증번호 확인
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              phone_number:
                type: string
              code:
                type: string
      responses:
        '200':
          description: 인증 성공
        '400':
          description: 인증 실패 또는 필수 입력 누락

  /verify-code-get-email:
    post:
      summary: 인증 후 이메일 확인
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              phone_number:
                type: string
              code:
                type: string
      responses:
        '200':
          description: 이메일 반환 성공
        '400':
          description: 인증번호 불일치
        '404':
          description: 사용자 없음
        '500':
          description: 서버 오류

  /verify-code-check-user:
    post:
      summary: 인증 후 사용자 확인
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              phone_number:
                type: string
              code:
                type: string
      responses:
        '200':
          description: 사용자 확인 완료
        '400':
          description: 인증번호 불일치
        '404':
          description: 사용자 없음
        '500':
          description: 서버 오류

  /patient/name:
    get:
      summary: 환자 이름 반환
      responses:
        '200':
          description: 이름 반환 성공
        '401':
          description: 인증 실패
        '404':
          description: 사용자 없음
        '500':
          description: 서버 오류

  /info-by-symptom:
    post:
      summary: 증상 기반 질병 정보 조회
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              symptom:
                type: string
                description: 검색할 증상명
      responses:
        '200':
          description: 질병 정보 조회 성공
        '400':
          description: 증상 누락
        '404':
          description: 매칭된 질병 없음
        '500':
          description: 서버 오류

  /chat/save:
    post:
      summary: AI 챗 저장 및 응답 생성
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              patient_text:
                type: string
                description: 환자 입력 메시지
      responses:
        '200':
          description: 챗 저장 및 AI 응답 반환
        '400':
          description: 필수 항목 누락
        '500':
          description: 서버 오류

  /request/availability-signcheck:
    get:
      summary: 의사 진료 가능 시간 + 수어 필요 여부 확인
      security:
        - JWT: []
      parameters:
        - in: query
          name: license_number
          required: true
          type: string
          description: Doctor's license number
      responses:
        '200':
          description: Reservations and sign language need info
        '400':
          description: License number required
        '404':
          description: Doctor or user not found
        '500':
          description: Server error

  /request/confirmed:
    post:
      summary: 진료 예약 확정
      security:
        - JWT: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - doctor_id
              - department
              - symptom_part
              - symptom_type
              - book_date
              - book_hour
              - sign_language_needed
            properties:
              doctor_id:
                type: integer
                description: Doctor ID
              department:
                type: string
                description: Department
              symptom_part:
                type: array
                items:
                  type: string
                description: Symptom part(s)
              symptom_type:
                type: array
                items:
                  type: string
                description: Symptom type(s)
              book_date:
                type: string
                description: Booking date (YYYY-MM-DD)
              book_hour:
                type: string
                description: Booking hour (e.g., "14:00")
              sign_language_needed:
                type: boolean
                description: Whether sign language is needed
      responses:
        '200':
          description: Reservation confirmed
        '400':
          description: Missing required reservation information
        '500':
          description: Server error

  /prescription/url:
    get:
      summary: 처방전 URL 반환
      security:
        - JWT: []
      parameters:
        - in: query
          name: diagnosis_id
          required: true
          type: string
          description: Diagnosis ID
      responses:
        '200':
          description: Prescription URL found
        '400':
          description: Diagnosis ID required
        '404':
          description: Prescription not found
        '500':
          description: Server error

  /diagnosis/list:
    get:
      summary: 진료 내역 반환
      security:
        - JWT: []
      responses:
        '200':
          description: List of diagnosis records
        '500':
          description: Server error

  /patient/default-address:
    get:
      summary: 환자 기본 주소 반환
      security:
        - JWT: []
      responses:
        '200':
          description: Default address info
        '404':
          description: User not found
        '500':
          description: Server error

  /delivery/register:
    post:
      summary: 배송 요청 등록
      security:
        - JWT: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - is_delivery
              - prescription_id
            properties:
              is_delivery:
                type: boolean
                description: Whether delivery is requested
              prescription_id:
                type: string
                description: Prescription ID
              address:
                type: string
                description: Delivery address
              postal_code:
                type: string
                description: Postal code
              patient_contact:
                type: string
                description: Patient contact
              pharmacy_id:
                type: string
                description: Pharmacy ID
              delivery_request:
                type: string
                description: Special delivery request
              is_default_address:
                type: boolean
                description: Set as default address
      responses:
        '200':
          description: Delivery registered
        '400':
          description: Required fields missing
        '500':
          description: Server error

  /delivery/complete:
    post:
      summary: 배송 완료 처리
      security:
        - JWT: []
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - delivery_id
            properties:
              delivery_id:
                type: string
                description: Delivery ID
      responses:
        '200':
          description: Delivery marked as received
        '400':
          description: Delivery ID required
        '404':
          description: Delivery not found
        '500':
          description: Server error

  /chat/add-separator:
    post:
      summary: 채팅 구분선 추가 및 정보 요약 저장
      security:
        - JWT: []
      responses:
        '200':
          description: Chat separator and summary info saved
        '400':
          description: Not enough chat history
        '500':
          description: Server error

  /chat/move-to-body:
    post:
      summary: 채팅 구분선 추가 후 외과 기반 진단으로 이동
      security:
        - JWT: []
      responses:
        '200':
          description: Moved to photo-based diagnosis
        '500':
          description: Server error

  /health-centers-with-doctors:
    get:
      summary: 주변 보건소 및 해당 의사 검색
      parameters:
        - name: lat
          in: query
          required: true
          type: string
          description: 위도
        - name: lng
          in: query
          required: true
          type: string
          description: 경도
        - name: department
          in: query
          required: true
          type: string
          description: 진료과
        - name: gender
          in: query
          required: false
          type: string
          description: 의사 성별 (선택)
      responses:
        '200':
          description: List of doctors at health centers
        '400':
          description: Missing or invalid parameters
        '404':
          description: No health centers found
        '500':
          description: Server error

  /pharmacies/nearby-info:
    get:
      summary: 약국 근처 상세 정보 통합 조회
      description: 위도, 경도를 기준으로 근처 약국 정보를 카카오 API로 조회하고, 자체 DB와 일치하는 약국의 상세 정보를 반환합니다.
      security:
        - JWT: []
      parameters:
        - name: lat
          in: query
          required: true
          type: string
          description: 위도 (Latitude)
        - name: lng
          in: query
          required: true
          type: string
          description: 경도 (Longitude)
      responses:
        200:
          description: 근처 약국 정보 리스트 반환
          schema:
            type: array
            items:
              type: object
              properties:
                pharmacy_id:
                  type: integer
                  description: 약국 ID
                pharmacy_name:
                  type: string
                  description: 약국 이름
                open_hour:
                  type: string
                  description: 운영 시작 시간
                close_hour:
                  type: string
                  description: 운영 종료 시간
                address:
                  type: string
                  description: 약국 주소
                contact:
                  type: string
                  description: 약국 전화번호
        '400':
          description: lat 또는 lng 파라미터 누락 혹은 형식 오류
        '401':
          description: 인증 실패 (JWT 필요)
        '500':
          description: 서버 오류 또는 Kakao API 오류