swagger: "2.0"
info:
  title: Silmedy_User
  version: 1.0.0
host: 192.168.0.170:5000
basePath: /
schemes:
  - http
paths:
  /request-verification-code:
    post:
      summary: 인증번호 요청
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              phone_number:
                type: string
      responses:
        '200':
          description: 인증번호 발송 성공
  /verify-code:
    post:
      summary: 인증번호 확인
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              phone_number:
                type: string
              code:
                type: string
      responses:
        '200':
          description: 인증 성공/실패
  /patient/signup:
    post:
      summary: 회원가입
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
              name:
                type: string
              contact:
                type: string
              postal_code:
                type: string
              birth_date:
                type: string
              address:
                type: string
              address_detail:
                type: string
              sign_language_needed:
                type: boolean
              is_default_address:
                type: boolean
      responses:
        '200':
          description: 회원가입 완료
  /postal_code:
    get:
      summary: 우편번호 검색
      parameters:
        - name: keyword
          in: query
          required: true
          type: string
      responses:
        '200':
          description: 우편번호 검색 결과
  /verify-code-get-email:
    post:
      summary: 인증번호 확인 및 아이디 확인
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              phone_number:
                type: string
              code:
                type: string
      responses:
        '200':
          description: 이메일 반환
  /verify-code-check-user:
    post:
      summary: 인증번호 확인 및 비밀번호 변경창 표시
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              phone_number:
                type: string
              code:
                type: string
      responses:
        '200':
          description: 사용자 존재 여부 확인
  /patient/repassword:
    post:
      summary: 비밀번호 변경
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              new_password:
                type: string
      responses:
        '200':
          description: 비밀번호 변경 완료
  /patient/login:
    post:
      summary: 로그인
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              password:
                type: string
      responses:
        '200':
          description: 로그인 성공/실패
  /request/disease-image:
    post:
      summary: 질병 이미지 로드
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              analysis:
                type: string
      responses:
        '200':
          description: 질병 설명 이미지 URL 반환
  /chat/save:
    post:
      summary: 채팅 저장
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              patient_id:
                type: integer
              patient_text:
                type: string
              ai_text:
                type: string
      responses:
        '200':
          description: 채팅 저장 완료
  /chat/add-separator:
    post:
      summary: 채팅 구분선 추가
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              patient_id:
                type: integer
      responses:
        '200':
          description: 구분선 추가 완료
  /request/doctors:
    get:
      summary: 의사 목록 조회
      parameters:
        - name: hospital_id
          in: query
          required: true
          type: integer
      responses:
        '200':
          description: 의사 목록 반환
  /request/availability:
    get:
      summary: 의사 진료 가능시간 확인
      parameters:
        - name: license_number
          in: query
          required: true
          type: string
      responses:
        '200':
          description: 진료 예약 가능 시간 반환
  /chat/signcheck:
    get:
      summary: 수어 필요 여부 자동 확인
      parameters:
        - name: patient_id
          in: query
          required: true
          type: integer
      responses:
        '200':
          description: 수어 필요 여부 반환
  /chat/confirmed:
    post:
      summary: 진료 예약 확정
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              patient_id:
                type: integer
              doctor_id:
                type: string
              department:
                type: string
              symptom_part:
                type: array
                items:
                  type: string
              symptom_type:
                type: array
                items:
                  type: string
              book_date:
                type: string
              book_hour:
                type: string
              sign_language_needed:
                type: boolean
      responses:
        '200':
          description: 진료 예약 확정 완료
  /call/waiting-doctor:
    post:
      summary: 전화 수신 대기
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              room_code:
                type: string
      responses:
        '200':
          description: 상태 변경 완료
  /call/doctor-id:
    post:
      summary: 의사 이름 로드
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              room_code:
                type: string
      responses:
        '200':
          description: 의사 정보 반환
  /call/add-patient-text:
    post:
      summary: 증상 설명 텍스트 저장
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              room_code:
                type: string
              patient_id:
                type: integer
              patient_text:
                type: string
      responses:
        '200':
          description: 증상 텍스트 저장 완료
  /call/latest-doctor-text:
    post:
      summary: 진료 텍스트 로드
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              room_code:
                type: string
      responses:
        '200':
          description: 최신 의사 텍스트 반환
  /call/end:
    post:
      summary: 전화 종료
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              room_code:
                type: string
      responses:
        '200':
          description: 전화 종료 완료
  /prescription/url:
    get:
      summary: 처방전 URL 반환
      parameters:
        - name: prescription_id
          in: query
          required: true
          type: integer
      responses:
        '200':
          description: 처방전 URL 반환
  /patient/default-address:
    get:
      summary: 기본 배송지 로드
      parameters:
        - name: patient_id
          in: query
          required: true
          type: integer
      responses:
        '200':
          description: 기본 배송지 반환
  /delivery/register:
    post:
      summary: 배송 신청 접수
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              patient_id:
                type: integer
              is_delivery:
                type: boolean
              patient_contact:
                type: string
              pharmacy_id:
                type: integer
              prescription_id:
                type: integer
              address:
                type: string
              postal_code:
                type: string
              delivery_request:
                type: string
              is_received:
                type: boolean
      responses:
        '200':
          description: 배송 신청 완료
  /delivery/complete:
    post:
      summary: 전달 완료 처리
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              delivery_id:
                type: integer
              patient_id:
                type: integer
      responses:
        '200':
          description: 배송 완료
  /patient/logout:
    post:
      summary: 로그아웃
      responses:
        '200':
          description: 로그아웃 완료
  /patient/delete:
    delete:
      summary: 회원 탈퇴
      parameters:
        - in: query
          name: patient_id
          required: true
          description: 탈퇴할 환자의 ID
          type: string
      responses:
        '200':
          description: 회원 탈퇴 완료
  /patient/update:
    post:
      summary: 회원 정보 수정
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              email:
                type: string
              updates:
                type: object
                properties:
                  password:
                    type: string
                  postal_code:
                    type: string
      responses:
        '200':
          description: 회원 정보 수정 완료
  /patient/mypage:
    get:
      summary: 회원 정보 조회
      parameters:
        - name: patient_id
          in: query
          required: true
          type: integer
      responses:
        '200':
          description: 회원 정보 반환
  /diagnosis/list:
    get:
      summary: 진료내역 로드
      parameters:
        - name: patient_id
          in: query
          required: true
          type: integer
      responses:
        '200':
          description: 진료내역 반환
